config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :categories
  resources :products
  resources :users
  resources :orders
  post 'products/add_to_cart/:id', to: 'products#add_to_cart', as: 'add_to_cart'

  delete 'products/remove_from_cart/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'

  # post 'products/cart', to: 'products#show_cart', as: 'show_cart'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true, length: { in: 3..20 }
end

app/models/order.rb
class Order < ApplicationRecord
  enum :order_status, {
    'New order': 'new_order',
    'Packaging': 'packaging',
    'Deliver in process': 'deliver_in_process',
    'Done': 'done'
  }, default: 'new_order'

  # belongs_to :user
  has_and_belongs_to_many :products

  validates :first_name, presence: true, length: { in: 2..10 }
  validates :last_name, presence: true, length: { in: 2..10 }
  validates :phone, presence: true, length: { in: 2..15 }
  validates :address, presence: true

end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :category, optional: true
  has_and_belongs_to_many :orders

  validates :name, presence: true, length: { in: 3..20 }
  validates :price, presence: true, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # has_many :orders

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :initialize_session, :load_cart

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name email phone])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name email phone])
  end

  def initialize_session
    session[:cart] ||= []
  end

  def load_cart
    @cart = Product.find(session[:cart])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = collection
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(categories_params)
    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def edit
    @category = resource
  end

  def update
    @category = resource

    if @category.update categories_params
      redirect_to categories_path, notice: 'Category was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category = resource
    @category.destroy
    redirect_to categories_path, notice: 'Category was successfully destroyed.'
  end

  private

  def collection
    Category.all
  end

  def resource
    collection.find(params[:id])
  end

  def categories_params
    params.require(:category).permit(:name)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    # @orders = collection
    @order = Order.new
  end

  def create
    @order = Order.new orders_params
    if @order.save
      redirect_to root_path, notice: 'Order was successfully created.'
    else
      render :index, status: :unprocessable_entity
    end
  end

  private

  def orders_params
    params.permit(:first_name, :last_name, :phone, :address, product_ids: [])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products or /products.json
  def index
    @products = collection
    # @cart = initialize_cart
    @order = initialize_order
  end

  # GET /products/1 or /products/1.json
  def show
    @product = resource
    # @cart = initialize_cart
  end

  # GET /products/new
  def new
    @product = Product.new
    # @cart = initialize_cart
  end

  # GET /products/1/edit
  def edit
    @product = resource
    # @cart = initialize_cart
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to product_url(@product), notice: 'Product was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    @product = resource

    if @product.update(product_params)
      redirect_to product_url(@product), notice: 'Product was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product = resource
    if session[:cart].exclude?(@product.id)
      @product.destroy
      flash[:notice] = 'Product was successfully destroyed.'
    else
      flash[:notice] = 'The product cannot be removed, it is in the shopping cart.'
    end

    redirect_to root_path
  end

  def add_to_cart
    id = params[:id].to_i
    session[:cart] << id unless session[:cart].include?(id)

    redirect_to root_path, notice: 'Product was successfully added to cart.'
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete(id)

    redirect_to root_path, notice: 'Product was successfully removed.'
  end

  private

  def collection
    Product.all
  end

  def resource
    collection.find(params[:id])
  end

  def initialize_order
    Order.new
  end

  def product_params
    params.require(:product).permit(:name, :category_id, :price, :description, :status)
  end
end

app/controllers/turbo_devise_user_controller.rb
class TurboDeviseUserController < ApplicationController
  class Responder < ActionController::Responder
     def to_turbo_stream
       controller.render(options.merge(formats: :html))
           rescue ActionView::MissingTemplate => error
       if get?
         raise error
       elsif has_errors? && default_action
         render rendering_options.merge(formats: :html,
             status: :unprocessable_entity)
       else
         redirect_to navigation_location
       end
     end
   end

   self.responder = Responder
   respond_to :html, :turbo_stream
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <div class="flex flex-row my-5">
    <div class="bg-slate-100  rounded-2xl border-2 shadow-x3 p-10 max-w-5xl">
      <div class="flex flex-col items-center space-y-4">
        <h3>Name: <%= category.name %></h3>

        <div class="text-center">
          <%= link_to "Edit this category", edit_category_path(category) %>
          <%# <%= link_to "Show this category", category_path(category) %>
          <%= button_to "Destroy this category", category, method: :delete,  data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<div class="flex justify-center ">
  <div class="bg-slate-100 rounded-2xl border-2 shadow-x3 pt-9 px-9  max-w-5xl">
    <div class="flex flex-col items-center space-y-4">

    <%= form_with(model: category) do |form| %>
      <div>
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name %>
      </div>

      <div class="rounded-lg py-3 my-5 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer flex justify-center">
        <%= form.submit %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-center my-10 text-4xl">Editing category</h1>

  <%= render "form", category: @category %>

  <div class="text-center mt-3">
    <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-4xl font-bold text-center my-10">Categories</h1>

<div id="categories" class="flex flex-row justify-around my-5">
  <% @categories.each do |category| %>
    <%= render category %>
  <% end %>
</div>
<div class="flex justify-center"><%= link_to "New category", new_category_path, class:"bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-2 mt-3 border border-blue-500 hover:border-transparent rounded"%>
</div>

app/views/categories/new.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold text-center my-10">New category</h1>
  <%= render "form", category: @category %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

    <div class="mt-0">
      <%= render 'shared/navbar'%>
    </div>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
      <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<div class="flex justify-center ">
  <div class="bg-slate-100 rounded-2xl border-2 shadow-x3 p-9 mb-10 max-w-5xl">
    <div class="flex flex-col items-center space-y-4">
    <%= form_with url:orders_path(product_ids: session[:cart]), class: "contents" do |form| %>

      <div class="my-5">
        <%= form.label :first_name %>
        <%= form.text_field :first_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>
      <div class="my-5">
        <%= form.label :last_name %>
        <%= form.text_field :last_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="my-5">
        <%= form.label :address %>
        <%= form.text_field :address, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="my-5">
        <%= form.label :phone %>
        <%= form.text_field :phone, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>
      <div class="inline">
        <%= form.submit class: "rounded-lg my-5 py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/orders/index.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold text-center my-10">Order</h1>
  <%= render "form", order: @order %>
</div>

app/views/products/_form.html.erb
<div class="flex justify-center ">
  <div class="bg-slate-100 rounded-2xl border-2 shadow-x3 p-10 max-w-5xl">
    <div class="flex flex-col items-center space-y-4">
      <%= form_with(model: product) do |form| %>
        <% if product.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
            <ul>
              <% product.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div>
          <%= form.label :name, style: "display: block" %>
          <%= form.text_field :name %>
        </div>

        <div>
          <%= form.label :category_id, style: "display: block" %>
          <%= form.select :category_id, Category.pluck(:name, :id), class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
        </div>

        <div>
          <%= form.label :price, style: "display: block" %>
          <%= form.text_field :price %>
        </div>

        <div class="text-center pt-10">
          <%= form.submit%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">

  <div class="flex justify-center my-5">
    <div class="bg-slate-100  rounded-2xl border-2 shadow-x3 p-10 max-w-5xl">
      <div class="flex flex-col items-center space-y-4">
        <h3>Name: <%= product.name %></h3>
        <h3>Category: <%= Category.find(product.category_id).name %></h3>
        <h3>Prise: <%= product.price %></h3>

        <div class="text-center">
          <%= link_to "Edit this product", edit_product_path(@product) %> |
          <%= link_to "Back to products", products_path %>
          <%= button_to "Destroy this product", @product, method: :delete,  data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/_table.html.erb
<table class="min-w-full text-center">
  <thead class="border-b bg-slate-400">
    <tr>
      <th scope="col" class="px-6 py-4 text-sm font-medium text-gray-900">
        Name
      </th>
      <th scope="col" class="px-6 py-4 text-sm font-medium text-gray-900">
        Category
      </th>
      <th scope="col" class="px-6 py-4 text-sm font-medium text-gray-900">
        Price
      </th>
      <th scope="col" class="px-6 py-4 text-sm font-medium text-gray-900">
        Action
      </th>
    </tr>
  </thead>
  <tbody>
    <% products.each do |product| %>
      <tr class="bg-indigo-100 border-b border-indigo-200">
        <td class="px-4 py-4 text-sm font-medium text-gray-900 whitespace-nowrap">
          <%= product.name %>
        </td>
        <% if product.category.nil? %>
        <td class="px-4 py-4 text-sm font-light text-gray-900 whitespace-nowrap">
        </td>
        <% else %>
        <td class="px-4 py-4 text-sm font-light text-gray-900 whitespace-nowrap">
          <%= product.category.name %>
        </td>
        <% end %>
        <td class="px-4 py-4 text-sm font-light text-gray-900 whitespace-nowrap">
          <%= number_to_currency(product.price, unit: "₴", delimiter: " ", format: "%n %u") %>
        </td>
        <td class="px-4 py-4 text-sm font-light text-gray-900 whitespace-nowrap">
          <% if action_name != "show" %>
            <%= link_to 'Show', product, class:"bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded"%>
            <%= link_to 'Edit', edit_product_path(product), class:"bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" %>
            <% if @cart.include?(product)%>
              <%= button_to 'Remove from cart', remove_from_cart_path(product), method: :delete,  class:"bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-2 mt-3 border border-blue-500 hover:border-transparent rounded" %>
             <% else %>
              <%= button_to 'Add to cart', add_to_cart_path(product.id), class:"bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-2 mt-3 border border-blue-500 hover:border-transparent rounded" %>
            <% end %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/edit.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold text-center my-10">Editing product</h1>

  <%= render "form", product: @product %>

</div>

app/views/products/index.html.erb
<%# <%= render 'products/cart'%>

<main class="container flex flex-col mx-auto mt-5">
  <div class="flex flex-col">
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <%# <%= render 'shared/cart'%>
        <%= render 'products/table', products: @products %>
        <%# <%= render 'orders/form', order: @order %>
      </div>
    </div>
  </div>
</div>
</main>

app/views/products/new.html.erb
<div class="w-full mx-auto md:w-2/3">
  <h1 class="text-4xl font-bold text-center my-10">New product</h1>

  <%= render "form", product: @product %>

</div>

app/views/products/show.html.erb
<%= render @product %>

app/views/shared/_cart.html.erb
<% if @cart.empty? %>
  <p class="text-black">No items in the cart</p>
<% else %>
  <ul class="text-black">
    <% @cart.each do |product| %>
      <li><%= product.name %>
    </li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-900">
  <div class="container flex flex-wrap items-center justify-between mx-auto">
    <a href="" class="flex items-center">
        <img src="https://flowbite.com/docs/images/logo.svg" class="h-6 mr-3 sm:h-9" alt="Flowbite Logo" />
        <span class="self-center text-xl font-semibold whitespace-nowrap dark:text-white">Products</span>
    </a>
    <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-default" aria-expanded="false">
      <span class="sr-only">Open main menu</span>
      <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
    </button>
    <div class="hidden w-full md:block md:w-auto" id="navbar-default">
      <ul class="flex flex-col p-4 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        <li>
          <%= link_to "Home", products_path, class:"block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white"%>
        </li>
        <li>
          <%= link_to "New product", new_product_path, class:"block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"%>
        </li>
        <li>
          <%= link_to "Categories", categories_path, class:"block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"%>
        </li>
        <li>
          <% if user_signed_in? %>
            <%= link_to current_user.first_name, current_user, class:"block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
            <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class:"block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
          <% else %>
            <%= link_to 'Sign up', new_user_registration_path, class:"block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent"%>
          <% end %>
        </li>
        <li>
          <%= render 'shared/popup_cart' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_popup_cart.html.erb
<div data-controller="modal">
  <button data-action="modal#open" class="btn-outline"><svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6 text-gray-700 hover:text-gray-200" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z" />
          </svg>
          <span class="absolute flex ml-4 -mt-6">
            <span class="absolute inline-flex w-3 h-3 bg-pink-400 rounded-full opacity-75 animate-ping"></span>
            <span class="relative inline-flex w-3 h-3 bg-pink-500 rounded-full"></span>
            </span></button>
  <dialog data-modal-target="modal" class="p-6">
    <button type="button" data-action="modal#close" class="absolute top-4 right-4">X</button>

    <h1>Shopping cart</h1>
    <hr class="mb-4">

    <form class="space-y-4">
      <%= render 'shared/cart' %>
      <div class="flex justify-end p-4 ">
        <button type="button" data-action="modal#close" class="px-5 py-2 m-3 text-white bg-indigo-500 rounded-md cursor-pointer hover:bg-indigo-700">
            Close</button>
        <% if @cart.present? %>
          <%= link_to 'Order', orders_path, class: "px-5 py-2 m-3 text-white bg-indigo-500 rounded-md cursor-pointer hover:bg-indigo-700"%>
        <% end %>
      </div>
    </form>
  </dialog>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<%= @user.first_name %>
<%= @user.last_name %>
<%= @user.email %>
<%= @user.phone %>